"""add_user_names

Revision ID: 20250721_120000
Revises: ffdc0a98111c
Create Date: 2025-07-21 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '20250721_120000'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # For SQLite, we need to add columns as nullable first, then update data
    op.add_column('users', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=50), nullable=True))
    
    # Update existing records with default values
    op.execute("UPDATE users SET first_name = 'Default', last_name = 'User' WHERE first_name IS NULL OR last_name IS NULL")
    
    # SQLite doesn't support ALTER COLUMN SET NOT NULL directly
    # We'll handle this constraint in the application layer
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###