"""Add user_id to business_images table

Revision ID: 2fd0a47606ec
Revises: 20250721_120004
Create Date: 2025-07-22 05:47:43.635718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fd0a47606ec'
down_revision = '20250721_120004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_images', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_business_images_user_id', 'business_images', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_business_images_user_id', 'business_images', type_='foreignkey')
    op.drop_column('business_images', 'user_id')
    # ### end Alembic commands ###
